### PR TITLE
5 lookup memory efficiency

### LINKED ISSUE #5: Improve memory efficiency of lookup in external CSV files
In this mapping job https://github.com/nkuehn/sphere-icecat-importer/blob/master/mapping_categories.yaml  
the memory used by the csv-mapper explodes quickly because of the large number of lookups in external csv files (which are dynamic data with thousands of lines and can therefore not be included as inline maps). 
It would be cool if that were not the case but probably tricky as the external lookup CSVs are all different.

### PR DESCRIPTION
**Pull request by nkuehn**
@OlegIlyenko  I have the impression that the actual transform shouldn't throw but just return the error here. Is that correct?  I introduced the throw because without it it was not possible to find out the Error cause when the tests fail. 

would fix #5

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
you are right, you shouldn't throw error. it may be fine within `then`, but for instance here:

https://github.com/sphereio/csv-mapper/pull/7/files#diff-c48457cd5d215f1321cd6290973c52f8R247

you should reject a promise instead of throwing an exception. Most of the codebase is using promises, so I would suggest to use promises here as well.

**Comment by nkuehn** [comment]
first part done, second later (I'm totally confused by the relationship of the Q() vs. node API promises / futrures etc. used).  It's probably a three-character thing for someone who is into the Q() library.

**Comment by nkuehn** [comment]
@OlegIlyenko  my brain is still not Q compatible again. I thought I can just wrap the calls into a Q() but the scope is not "this" any more. 

```
    else
      Q().then ->
        @_setColumnIdx()
        @_buildLookupMap()
        this
```

feeling very dumb

**Comment by emmenko** [comment]
You probably need to use fat arrow `=>`

**Comment by nkuehn** [comment]
@emmenko if it were ES6 yes. But it's coffee :-(

**Comment by OlegIlyenko** [comment]
Coffeescript has -> and => as well (with the same semantics)

**Comment by emmenko** [comment]
`=>` in coffeescript binds `this`

**Comment by nkuehn** [comment]
right. I should have RTFM.  

side note: there seem to be very varying opinions of whether the fat/thin arrows in coffee & ES6 are actually the same:  https://www.airpair.com/coffeescript/posts/migrating-coffeescript-to-es6-javascript   ( this guy says: "ES6 JavaScript has no thin arrow function ->. Essentially, CoffeeScript -> == ES6 =>").  

Anyhow, thanks for the help.

**Comment by OlegIlyenko** [comment]
ah, ok, good to know! It's a pity, since i strongly believe that coffescript `⇒` should be the default... can't imagine working without it. If ES6 does not have it at all, then it probably should be very frustrating

**Comment by nkuehn** [comment]
I'm done now.  promises should be OK now and my lookup-critical job (joining category name and description translations into the categories import) is down from 1.4GB->out of memory to  between 200 and 320MB.

**Comment by nkuehn** [comment]
ping @OlegIlyenko  any opinions on whether to merge this?  (I'm just cleaning up old open issues, no specific urgent need).

**Comment by OlegIlyenko** [comment]
@nkuehn sure, I'll review an mergit. Sorry, I missed your previous comment. Thanks for reminding me.

**Comment by OlegIlyenko** [comment]
Thanks a lot for this improvement. I will release it with the next version shortly.

**Comment by nkuehn** [comment]
thank you!

**Comment by OlegIlyenko** [comment]
Released: https://github.com/sphereio/csv-mapper/releases/tag/v1.0.9

**Comment by nkuehn** [comment]
+1

**Pull request merged**
